Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,18 +1,40 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
+# **************************************************************************************************************** #
+# This workflow will install Python dependencies, and run pytest --cov on all files recursively from the pytest-root-dir
+# The workflow is also configured to exit with error if minimum individual file or total pytest coverage minimum not met
+# If the workflow exits with error, an informative issue is created for the repo alerting the user
+# If the workflow succeeds, a commit message is generated with the pytest --cov markdown table
+#
+# Variables to set:
+#   * pytester action:
+#     * pytest-root-dir: top-level directory to recursively check all .py files for pytest --cov
+#     * cov-omit-list: comma separated str of all files and/or dirs to ignore
+#   * env:
+#     * cov-threshold-single: minimum individual file coverage required
+#     * cov-threshold-total: minimum total coverage required
+#
+# Action outputs:
+#   * output-table: `pytest --cov` markdown output table
+#   * cov-threshold-single-fail: `false` if any single file coverage less than `cov-threshold-single`, else `true`
+#   * cov-threshold-total-fail: `false` if total coverage less than `cov-threshold-total`, else `true`
+#
+# Workflows used:
+#   * actions/checkout@v2: checkout files to perform additional actions on
+#   * alexanderdamiani/pytester-cov@v1.0.0: runs pytest --cov and associated functions
+#   * nashmaniac/create-issue-action@v1.1: creates issue for repo
+#   * peter-evans/commit-comment@v1: adds message to commit
+# **************************************************************************************************************** #
 
-name: Python application
+name: Pytester workflow
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+on: [push, pull_request]
 
 jobs:
   build:
 
     runs-on: ubuntu-latest
+    env:
+      COVERAGE_SINGLE: 60
+      COVERAGE_TOTAL: 60
 
     steps:
     - uses: actions/checkout@v2
@@ -26,12 +48,49 @@ jobs:
         pip install flake8 pytest
         pip install requests
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: Lint with flake8
+
+    - name: pytester-cov
+      id: pytester-cov
+      uses: alexanderdamiani/pytester-cov@v1.0.0
+      with:
+        pytest-root-dir: '.'
+        cov-omit-list: ''
+        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+
+    - name: Coverage single fail - new issue
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+      uses: nashmaniac/create-issue-action@v1.1
+      with:
+        title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+        token: ${{secrets.GITHUB_TOKEN}}
+        assignees: ${{github.actor}}
+        labels: worflow-failed
+        body: ${{ steps.pytester-cov.outputs.output-table }}
+
+    - name: Coverage single fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-    - name: Test with pytest
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+        exit 1
+
+    - name: Coverage total fail - new issue
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+      uses: nashmaniac/create-issue-action@v1.1
+      with:
+        title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+        token: ${{secrets.GITHUB_TOKEN}}
+        assignees: ${{github.actor}}
+        labels: worflow-failed
+        body: ${{ steps.pytester-cov.outputs.output-table }}
+
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
       run: |
-        pytest tests
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
+
+    - name: Commit pytest coverage table
+      uses: peter-evans/commit-comment@v1
+      with:
+        body: ${{ steps.pytester-cov.outputs.output-table }}
